project:
  type: website

website:
  title: "A technical ML blog"
  site-url: https://kunschg.github.io/blog/
  description: "Tutorials, articles and random thoughts on AI landscape, from maths to LLM"
  navbar:
    right:
      - text: "About"
        href: https://gkunsch.fr/
      - icon: github
        href: https://github.com/kunschg
      - icon: linkedin
        href: https://www.linkedin.com/in/guillaume-kunsch-1146bb151/
      - icon: rss
        href: index.xml
  page-footer: "Copyright 2023, Guillaume Kunsch" 
  google-analytics: "G-F7QP106X85"

  sidebar:
    - id: articles
      title: "Articles"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "🌐 **Hyperbolic embeddings**"
          contents:
            - text: "1. Non-euclidean geometry"
              href: 
        - text: "---"
        - section: "🥇 **Maths**"
          contents:
            - text: "1. Fisher Information"
              href: posts/fisher_information/index.html
        - text: "---"
        - section: "🗣️ **Large language models**"
          contents:
            - text: "1. What are Transformers ?"
              href: 

format:
  html:
    page-layout: article
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 2
    toc-title: "**Sections**"


