project:
  type: website

website:
  title: "A technical ML blog"
  site-url: https://kunschg.github.io/blog/
  description: "Tutorials, articles and random thoughts on AI landscape, from maths to LLM"
  navbar:
    right:
      - text: "About"
        href: https://gkunsch.fr/
      - icon: github
        href: https://github.com/kunschg
      - icon: linkedin
        href: https://www.linkedin.com/in/guillaume-kunsch-1146bb151/
      - icon: rss
        href: index.xml
  page-footer: "Copyright 2023, Guillaume Kunsch" 
  google-analytics: "G-F7QP106X85"

  sidebar:
    - id: articles
      title: "Articles"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "🌐 **Hyperbolic embeddings**"
          contents:
            - text: "1. To-Do"
              href: posts/hello_world.html
        - text: "---"
        - section: "🥇 **Maths stuff**"
          contents:
            - text: "1. Linear Programming"
              href: posts/hello_world.html
        - text: "---"
        - section: "🗣️ **Large language models**"
          contents:
            - text: "1. Intro "
              href: posts/hello_world.html

format:
  html:
    theme: cosmo
    css: styles.css



