project:
  type: website
  output-dir: docs

website:
  title: "A technical ML blog"
  site-url: https://kunschg.github.io/blog/
  description: "A great sample blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css



