project:
  type: website

website:
  title: "A technical ML blog"
  site-url: https://kunschg.github.io/blog/
  description: "Tutorials, articles and random thoughts on AI landscape, from maths to LLM"
  navbar:
    right:
      - text: "About"
        href: https://gkunsch.fr/
      - icon: github
        href: https://github.com/kunschg
      - icon: linkedin
        href: https://www.linkedin.com/in/guillaume-kunsch-1146bb151/
      - icon: rss
        href: index.xml
  page-footer: "Copyright 2023, Guillaume Kunsch" 
  google-analytics: "G-F7QP106X85"
  bread-crumbs: false
  comments: 
    utterances:
      repo: blog
      theme: github-light

  sidebar:
    - id: articles
      title: "Articles"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "🤖 **Machine Learning**"
          contents:
            - text: "1. Hyperbolic embeddings"
              href: posts/hyperbolic_embeddings/index.html
        - text: "---"
        - section: "🛠️ **Maths**"
          contents:
            - text: "1. Fisher Information"
              href: 

format:
  html:
    page-layout: article
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-title: "**Sections**"


